In [1]:
import numpy as np

In [70]:
def vector_dot_product(w, inp):
    assert len(w) == len(inp), "Input lengths must match!"
    return np.dot(w, inp)

In [71]:
x = [1, 2, 3, 4]
w = [1, 2, 3, 4]

out = vector_dot_product(w, x)

In [74]:
def single_perceptron_single_output(x, w):
    return dot_product(w, x)

In [75]:
def single_perceptron(weights, inputt):
    if isinstance(weights, list):
        weights = np.array(weights)
    if isinstance(inputt, list):
        inputt = np.array(inputt)

    return inputt.dot(weights)

In [90]:
# Multiple input, single output

In [91]:
single_perceptron([1, 2, 3, 4], [1, 2, 3, 4])

30

In [92]:
w = np.array([4, 2, 3, 4]).reshape(-1, 4)
x = np.array([7])

In [93]:
np.dot(w.T, x)

array([28, 14, 21, 28])

In [94]:
# Single input, multiple output

In [95]:
single_perceptron(w, x)

array([28, 14, 21, 28])

In [96]:
# Multiple input, multiple output

In [106]:
# rows indicate consecutive neurons, columns indicate subsequent input features
w = np.array([[0.2, 0.3, 0.4], [0.15, 0.6, 0.7], [0.1, 0.0, 0.5]])

# an input with three features
inputt = np.array([1, 2, 3])

In [99]:
def neural_network(w, inputt):
    return np.dot(w, inputt)

In [103]:
neural_network(w, inputt)

array([2.  , 3.45, 1.6 ])

In [105]:
assert np.dot(w[0], inputt) == 2.

In [108]:
print(f"Output of first neuron: {np.dot(w[0], inputt)}")
print(f"Output of second neuron: {np.dot(w[1], inputt)}")
print(f"Output of third neuron: {np.dot(w[2], inputt)}")

Output of first neuron: 2.0
Output of second neuron: 3.4499999999999993
Output of third neuron: 1.6


In [127]:
feature1 = [8.5, 9.5, 9.9, 9.0]
feature2 = [0.65, 0.8, 0.8, 0.9]
feature3 = [1.2, 1.3, 0.5, 1.0]

In [128]:
l1 = np.array([[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]])
l2 = np.array([[0.3, 1.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]])

In [170]:
def forward(inputt):
    l1_output = np.dot(inputt, l1.T)
    output = np.dot(l1_output, l2.T)
    return output

In [171]:
input1 = [feature1[0], feature2[0], feature3[0]]

In [172]:
forward(input1)

array([0.2135, 0.145 , 0.5065])